update GH actions workflows

diff --git a/.github/workflows/build_status.yml b/.github/workflows/build_status.yml
--- a/.github/workflows/build_status.yml
+++ b/.github/workflows/build_status.yml
@@ -6,47 +6,51 @@ on:
   pull_request:
 
 env:
-  JAVA_VERSION: 21
-  GRADLE_BUILD_CACHE_USER: ${{ secrets.GRADLE_BUILD_CACHE_USER }}
-  GRADLE_BUILD_CACHE_TOKEN: ${{ secrets.GRADLE_BUILD_CACHE_TOKEN }}
+  JAVA_VERSION: 25
 
 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v4
+      - uses: actions/checkout@v6
       - name: Set up JDK ${{ env.JAVA_VERSION }}
-        uses: actions/setup-java@v4
+        uses: actions/setup-java@v5
         with:
-          distribution: 'microsoft'
           java-version: ${{ env.JAVA_VERSION }}
+          distribution: 'microsoft'
       - name: Setup Gradle
-        uses: gradle/actions/setup-gradle@v4
+        uses: gradle/actions/setup-gradle@v5
+        with:
+          cache-encryption-key: ${{ secrets.GRADLE_CONFIG_CACHE_ENCRYPTION_KEY }}
       - name: Grant execute permission for gradlew
         run: chmod +x ./gradlew
       - name: Build with Gradle
-        run: ./gradlew build --rerun-tasks
+        run: ./gradlew assemble --rerun-tasks
       - name: Upload build artifacts (Common)
-        uses: actions/upload-artifact@v4
         continue-on-error: true
+        uses: actions/upload-artifact@v6
         with:
           name: ${{ github.event.repository.name }}-Common-${{ github.sha }}
           path: |
             Common/build/libs/*.jar
-            !Common/build/libs/*-dev.jar
-      - name: Upload build artifacts (Forge)
-        uses: actions/upload-artifact@v4
-        continue-on-error: true
-        with:
-          name: ${{ github.event.repository.name }}-Forge-${{ github.sha }}
-          path: |
-            Forge/build/libs/*.jar
-            !Forge/build/libs/*-dev.jar
       - name: Upload build artifacts (Fabric)
-        uses: actions/upload-artifact@v4
         continue-on-error: true
+        uses: actions/upload-artifact@v6
         with:
           name: ${{ github.event.repository.name }}-Fabric-${{ github.sha }}
           path: |
             Fabric/build/libs/*.jar
-            !Fabric/build/libs/*-dev.jar
+      - name: Upload build artifacts (Forge)
+        continue-on-error: true
+        uses: actions/upload-artifact@v6
+        with:
+          name: ${{ github.event.repository.name }}-Forge-${{ github.sha }}
+          path: |
+            Forge/build/libs/*.jar
+      - name: Run tests
+        run: ./gradlew check
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@ee6b445351cd81e2f73a16a0e52d598aeac2197f # v5.3.0
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/build/test-results/test/TEST-*.xml'
